### ISSUE TITLE
Unable to add .

### ISSUE THREAD

**Issue by wekempf** [WCOMAB/Cake_Git#19]
I'm trying to add all pending changes, the equivalent of:

git add .

My repo is in a subdirectory, so I'm doing the following:

GetAdd("./clone", new FilePath[] { "./clone" });

I've tried everything I can think of for the second parameter, all to no avail. With a little playing around I think the issue is with how this relative path is converted.

```
    var file = File("./clone").Path.MakeAbsolute(Context.Environment);
    var dir = Directory("./clone").Path.MakeAbsolute(Context.Environment);
    Information(dir.GetRelativePath(file).FullPath);
```

This produces "../clone" rather than ".". Am I missing something obvious, or do we have a bug that needs to be fixed here?

**Comment by devlead** [comment]
Issue is because add that's a file path and not a string. Libgit2sharp doesn't have `.` concept.
What would be possible though would be to add an alias to stage all pending changes something like a `GitAddAll(repopath)` that does something like below internally
```csharp
    context.UseRepository(
        repositoryDirectoryPath,
        repository =>  Commands.Stage(repository, "*")
    );
```

Would be an small addition to [GitAliases.Add.cs](https://github.com/WCOMAB/Cake_Git/blob/master/src/Cake.Git/GitAliases.Add.cs#L62)

**Comment by devlead** [comment]
There's now an GitAddAll
